version: "3.8"
services:
  webshop-dbms:
    build:
      context: ./sql
      dockerfile: Dockerfile
    volumes:
      - "./.data/db:/var/lib/mysql"
    container_name: webshop-dbms
    restart: always
    ports:
      - "3306:3306"
    networks:
      webshop-network:
        aliases:
          - webshop-dbms

  usermanagement:
    build:
      context: ./microservices/usermanagement
      dockerfile: Dockerfile
    depends_on:
      - webshop-dbms
    container_name: usermanagement
    restart: always
    ports:
      - "8080:8080"
    networks:
      - webshop-network

  categorymanagement:
    build:
      context: ./microservices/categorymanagement
      dockerfile: Dockerfile
    depends_on:
      - webshop-dbms
    container_name: categorymanagement
    restart: always
    ports:
      - "8081:8081"
    networks:
      - webshop-network

  productmanagement:
    build:
      context: ./microservices/productmanagement
      dockerfile: Dockerfile
    depends_on:
      - webshop-dbms
    container_name: productmanagement
    restart: always
    ports:
      - "8082:8082"
    networks:
      - webshop-network

networks:
  webshop-network:
    driver: bridge
