version: "3"
services:
  webshop-dbms:
    image: mysql:latest
    environment:
      MYSQL_DATABASE1: category_service
      MYSQL_DATABASE2: product_service
      MYSQL_DATABASE3: user_service
      MYSQL_ROOT_PASSWORD: root
    build:
      context: ./sql
      dockerfile: Dockerfile
    volumes:
      - "./.data/db:/var/lib/mysql"
    container_name: webshop-dbms
    ports:
      - "3306:3306"
    networks:
      webshop-network:
        aliases:
          - webshop-dbms
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5

  usermanagement:
    build:
      context: ./microservices/usermanagement
      dockerfile: Dockerfile
    depends_on:
      webshop-dbms:
        condition: service_healthy
    container_name: usermanagement
    ports:
      - "8080:8080"
    networks:
      - webshop-network

  categorymanagement:
    build:
      context: ./microservices/categorymanagement
      dockerfile: Dockerfile
    depends_on:
      webshop-dbms:
        condition: service_healthy
    container_name: categorymanagement
    ports:
      - "8081:8081"
    networks:
      - webshop-network

  productmanagement:
    build:
      context: ./microservices/productmanagement
      dockerfile: Dockerfile
    depends_on:
      webshop-dbms:
        condition: service_healthy
    container_name: productmanagement
    ports:
      - "8082:8082"
    networks:
      - webshop-network

networks:
  webshop-network:
    driver: bridge
