version: "3"
services:
  webshop-dbms:
    image: mysql:latest
    environment:
      MYSQL_DATABASE1: category_service
      MYSQL_DATABASE2: product_service
      MYSQL_DATABASE3: user_service
      MYSQL_ROOT_PASSWORD: root
    build:
      context: ./sql
      dockerfile: Dockerfile
    volumes:
      - ./sql/create-tables.sql:/docker-entrypoint-initdb.d/create-tables.sql
      - ./sql/initial.sql:/docker-entrypoint-initdb.d/initial.sql
    container_name: webshop-dbms
    ports:
      - "3306:3306"
    networks:
      webshop-network:
        aliases:
          - webshop-dbms

  usermanagement:
    build:
      context: ./microservices/usermanagement
      dockerfile: Dockerfile
    depends_on:
      - webshop-dbms
    container_name: usermanagement
    ports:
      - "8080:8080"
    networks:
      - webshop-network

  categorymanagement:
    build:
      context: ./microservices/categorymanagement
      dockerfile: Dockerfile
    depends_on:
      - webshop-dbms
    container_name: categorymanagement
    ports:
      - "8081:8081"
    networks:
      - webshop-network

  productmanagement:
    build:
      context: ./microservices/productmanagement
      dockerfile: Dockerfile
    depends_on:
      - webshop-dbms
    container_name: productmanagement
    ports:
      - "8082:8082"
    networks:
      - webshop-network

networks:
  webshop-network:
    driver: bridge
